apiVersion: cpu.example.com/v1alpha1
kind: NodeCPUTopology
metadata:
  name: pegasus.fm2aihpcsed.com
  namespace: cpu-operator-system
spec:
  nodeName: pegasus.fm2aihpcsed.com
status:
  nodeName: pegasus.fm2aihpcsed.com
  topologyReady: true
  onlineCPUs: "0-343"
  numaNodes:
    - id: 0
      cpus: "0-42,172-214"
      memoryMiB: 512000
    - id: 1
      cpus: "43-85,215-257"
      memoryMiB: 512000
    - id: 2
      cpus: "86-128,258-300"
      memoryMiB: 512000
    - id: 3
      cpus: "129-171,301-343"
      memoryMiB: 512000
